### add a goal
POST http://localhost:5000/api/goal/add
content-type: application/json

{
  "user": "admin@debloat.us",
  "movement": "Meditation",
  "quantity": 360,
  "unit": "min",
  "plan": "accu",
  "timeFrame": 90,
  "start": "2022-march-20",
  "notes": "daily meditation"
}

### get goals
POST http://localhost:5000/api/goal
content-type: application/json

{
  "email": "admin@debloat.us"
}

### edit a goal
PUT http://localhost:5000/api/goal
content-type: application/json

{
  "user": "admin@debloat.us",
  "movement": "run",
  "quantity": "8000"

}
