### add a workout
POST http://localhost:5000/api/log/
Content-Type: application/json

{
  "user": "admin@debloat.us",
  "movement": "Snatch",
  "rep": 3,
  "sets": 3,
  "weight": 100,
  "unit": "kgs",
  "duration": ""
}

### get all logs
GET http://localhost:5000/api/log/
Content-Type: application/json

{
  "user": "miguel@debloat.us"
}

### edit a workout
PUT http://localhost:5000/api/log/622637d5c7180d522ed8d9ae
Content-Type: application/json

{
  "movement": "Clean and Jerk"
}
