export const profileBanner = [
	{text:'“To keep the body in good health is a duty – otherwise, we shall not be able to keep our mind strong and clear.”', author: 'Buddha'},
	{text:'“Some people want it to happen, some wish it would happen, others make it happen.”' , author: 'Michael Jordan'},
	{text:'“There’s no secret formula. I lift heavy, work hard, and aim to be the best.”' , author: 'Ronnie Coleman'},
	{ text: "“Living a healthy lifestyle will only deprive you of poor health, lethargy, and fat.”", author: 'Jill Johnson' },
	{ text: "“Physical fitness is not only one of the most important keys to a healthy body, it is the basis of dynamic and creative intellectual activity.”", author: "John F. Kennedy" },
	{ text: "“Success is usually the culmination of controlling failure.”", author: "Sylvester Stallone" },
	{ text: "“You shall gain, but you shall pay with sweat, blood, and vomit.”", author: "Pavel Tsatsouline" },
	{ text: "“Pain is temporary. Quitting lasts forever.”", author: "Lance Armstrong" },
	{ text: "“Tough times don’t last. Tough people do.”", author: "Robert H. Schuller" },
	{ text: "“If you aren’t going all the way, why go at all?”", author: "Joe Namath" },
	{ text: "“Set your goals high, and don’t stop till you get there.”", author: "Bo Jackson" },
	{ text: "“Persistence can change failure into extraordinary achievement.”", author: "Marv Levy" },
	{ text: "“Every champion was once a contender that refused to give up.”", author: "Rocky Balboa" },
	{ text: "“Age is no barrier. It’s a limitation you put on your mind.”", author: "Jackie Joyner-Kersee" },
	{ text: "“One man practicing sportsmanship is far better than 50 preaching it.”", author: "Knute Rockne" },
	{ text: "“The only person you are destined to become is the person you decide to be.”", author: "Ralph Waldo Emerson" },
	{ text: "“Strength does not come from physical capacity. It comes from an indomitable will.”", author: "Mahatma Gandhi" },
	{ text: "“Obstacles don’t have to stop you. If you run into a wall, don’t turn around and give up.Figure out how to climb it, go through it, or work around it.”", author: "Michael Jordan" },
	{ text: "“If you are afraid of failure you don’t deserve to be successful!”", author: "Charles Barkley" },
	{ text: "“Do not let what you can not do interfere with what you can do.”", author: "John Wooden" },
	{ text: "“A champion is afraid of losing. Everyone else is afraid of winning.”", author: "Billie Jean King" },
	{ text: "“What do you do with a mistake: recognize it, admit it, learn from it, forget it.”", author: "Dean Smith" },
	{ text: "“I’ve failed over & over & over again in my life & that is why I succeed.”", author: "Michael Jordan" },
	{ text: "“You can’t get much done in life if you only work on the days when you feel good.”", author: "Jerry West" },
	{ text: "“Today I will do what others won’t, so tomorrow I can accomplish what others can’t.”", author: "Jerry Rice" },
	{ text: "“It’s hard to beat a person who never gives up.” “Heroes get remembered, but legends never die.”", author: "Babe Ruth" },
	{ text: "“I’ve got a theory that if you give 100% all of the time, somehow things will work out in the end.”", author: "Larry Bird" },
	{ text: "“The key is not the will to win. Everybody has that. It is the will to prepare to win that is important.”", author: "Bobby Knight" },
	{ text: "“I don’t plan on being disappointed. We plan on being really good, and obviously, we plan on winning.”", author: "Gregg Troy" },
	{ text: "“You might not be able to outthink, out the market or outspend your competition, but you can outwork them.”", author: "Lou Holtz" },
	{ text: "“You have to do something in your life that is honorable and not cowardly if you are to live in peace with yourself.”", author: "Larry Brown" },

];

export const afterALog = [
"“Success trains. Failure complains.”",
"“Look in the mirror. That’s your competition.”",
"“The sweat. The time. The devotion. It pays off.”",
"“You are the only one who can limit your greatness.”",
];
